data:
    mmap_root: /home/sphenix_fm/data/pp_100k_mmap-with_charge
    gnn: true
    target: seg
data_processor:
    num_knn_neighbors     : 100
    knn_query_fraction    : 0.02
    random_query_fraction : 0.02
    continuous_phi        : True
    radius_normalizer     : 48
checkpointing:
    checkpoint_path: ./checkpoints
    save_frequency: 10
    resume: true
train:
    num_epochs: 30 # parameter value from the repo
    batch_size: 4
